version: '3.4'

services:
  db:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: solidplan
      MYSQL_DATABASE: solidplan
    volumes:
      - ./var/db:/var/lib/mysql:rw
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
      target: api
    environment:
      SYMFONY_PROJECT_NAME: solidplan
      DATABASE_URL: mysql://root:solidplan@db:3306/solidplan
      CORS_ALLOW_ORIGIN: "^https?://localhost(:[0-9]+)?"
      JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
    command: local:server:start --allow-http --port=8000 --no-tls
    depends_on:
      - db
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
      target: ui
    ports:
      - '8085:3000'
    environment:
      API_PROXY_URL: "http://api:8000"
    depends_on:
      - api
